// import React here?

// ORGANIZE THESE IMPORTS
import type { NextPage } from "next";
// import { FormEvent } from "react";
import {
  useState,
  useEffect,
  ChangeEvent,
  FormEvent,
  Dispatch,
  SetStateAction,
  useRef,
} from "react";

import Head from "next/head";
// utlize this in the picture grid and also for clicking individual pictures
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { getPhotosMiddleware, FormattedPhoto } from "../apiMiddleware";

import { useScrollHeight } from "../customHooks/useScrollHeight";

// import throttle from "lodash/throttle";

type FormattedPhotos = [FormattedPhoto] | [];

const submitForm = (
  searchTerm: string,
  setPhotos: Dispatch<SetStateAction<FormattedPhotos>>,
  lastFetched: { current: number }
  // setTimeStamp: Dispatch<SetStateAction<number>>
) => {
  // should this function get a flag called reset that resets currentPage
  // eg if the searchTerm changes?
  getPhotosMiddleware({ searchTerm })
    .then((res) => {
      const {
        formattedPhotos,
        pagesLeft,
        totalPhotos,
        currentPage,
        timeStamp,
      } = res;
      console.log({ pagesLeft, totalPhotos, currentPage, timeStamp, res });
      // IF PAGES LEFT IS A NEGATIVE
      // IF PAGES LEFT === -1 then no results were returned --> handle this with some sort of front end error

      // debugger;
      // only set photos here if they exist?
      // setTimeStamp(timeStamp);
      lastFetched.current = timeStamp;
      setPhotos(
        (prevPhotos) => [...prevPhotos, ...formattedPhotos] as FormattedPhotos
      );
    })
    .catch((e) => console.log(e));
};

// pull concat additonal photos out of render cycle?

const Home: NextPage = () => {
  const [searchInput, setSearchInput] = useState<string>("");
  const [photos, setPhotos] = useState<FormattedPhotos>([]);
  // const [lastFetched, setLastFetched] = useState<number>(0);
  const lastFetched = useRef<number>(0);

  const currentScrollHeight = useScrollHeight();
  console.log({ currentScrollHeight });

  // THIS USE EFFECT IS HITTING EVERY TIME WE THE SCROLL HITS
  useEffect(() => {
    const imgContainerNodeScrollHeight =
      document.getElementById("imageContainer")?.scrollHeight || 0;

    const shouldFetch =
      imgContainerNodeScrollHeight - currentScrollHeight < 2000 &&
      !!photos.length &&
      lastFetched.current !== 0 &&
      lastFetched.current + 2000 <= Date.now();

    console.log({
      shouldFetch,
      lastFetched: lastFetched.current,
      now: Date.now(),
    });

    // at the bottom - no more photos left if totalPhots === photos.length
    if (shouldFetch) {
      submitForm(searchInput, setPhotos, lastFetched);
    }
  }, [currentScrollHeight, lastFetched, photos.length, searchInput]);

  // update the id of the image container when you make this more modular and make components for everything
  return (
    <div className={styles.container} id="imageContainer">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form
        onSubmit={(e: FormEvent<HTMLFormElement>) => {
          e.preventDefault();
          // reset photos array here for a new form submit?
          submitForm(searchInput, setPhotos, lastFetched);
        }}
      >
        <input
          type="text"
          placeholder="search term"
          onChange={(e: ChangeEvent<HTMLInputElement>) =>
            setSearchInput(e.target.value)
          }
        />
        {/* disable button based on there being an actual input*/}
        <button type="submit">Search Photos</button>
      </form>
      {photos.map(({ height, width, id, urls }, i) => {
        const { full, raw, regular, small } = urls;
        return (
          // <div key={`${id}_${i}`}>
          <div key={`${id}`}>
            {/* <Image src={small} quality={100} height={400} width={400} alt="" /> */}
            {/* mess with this height/ width in order to get images to load in faster? */}
            <Image
              src={small}
              quality={100}
              layout="responsive"
              height={height}
              width={width}
              alt=""
            />
          </div>
        );
      })}
    </div>
  );
};

export default Home;
